# Generated by Django 4.0.6 on 2022-07-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
